version: '3.8'

services:
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PGPORT}:5555"  
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "${REDISPORT}:6379"
    volumes:
      - redis_volume:/data
    command: redis-server --appendonly yes  

volumes:
  psql_volume_bp:
  redis_volume:

